### ISSUE TITLE
Code Comments

### ISSUE THREAD

**Issue by cmvanmeter** [aaronmueller/zsh-P4#12]
I have left several comments in my fork about the format/general information. There are some pieces that I do not fully understand. Is it possible to explain the purpose of segments using comments? I've pointed out where they might be useful.

**Comment by aaronmueller** [comment]
I'll go ahead and explain in detail here, and I can add comments within the loop if you'd like me to explain more specific parts. The for loop in readAndTokenize() that you commented is the loop that goes through the input line char-by-char, tokenizing each space-separated word into separate entries of the `tokens` array. The first if statement places the token into the `tokens` array; the first else-if deals with the end of the user input line; and the final else-if deals with the start of the new token.

The while loop in main() that you commented is the loop that keeps the program going until the `done` command is entered. It's where the actual user interaction and input handling happens. 

I honestly can't explain the `waitpid` stuff. Even after reading the man pages, I'm unfamiliar with how to actually use it, to be honest. Change that however you see fit.

Would it be better to use scanf() instead of fgets() to prevent overflow? I was under the impression that the size limit given by the MAXLEN argument would prevent it from reading anything more than 1024 chars.

Let me know if I missed anything or if you'd like more info about anything here.
