### ISSUE TITLE
Overflowing fgets

### ISSUE THREAD

**Issue by cmvanmeter** [aaronmueller/zsh-P4#3]
(1) How were the values of MAXLEN and MAXTOKENS determined?
Currently, exceeding fgets(line, MAXLEN, stdin) results in an additional number of ">" being printed. It is possible that the input is interpreted as additional "lines" that could possibly be executed.
Not dangerous at the moment since do et. al. are defanged, but this needs to be fixed before additional functionality is added.

Need to test: malloc -- is it safe?

**Comment by aaronmueller** [comment]
On my phone because airport wifi is the worst (forgive any typos): 

MAXLEN and MAXTOKENS are arbitrary numbers. Those are just numbers that seemed good when initially starting the project; feel free to change things. 

Would it be better to use scanf instead of fgets? I was under the impression that there was a byte limit imposed by the MAXLEN argument of fgets, but if this is not the case, we can use scanf if it would better protect against overflow. 

Also, malloc() is totally unsafe and prone to memory leaks until I add a method to free all entries in the tokens array (I'll open an issue for this). This doesn't seem hard, but when I try making a simple method that goes through the array and frees everything that isn't null, it seems fine at first; however, if you press the delete key after the program stops with a 'done' command, tons of prompts print and my computer completely crashes. So yeah, that'll be something I'm focusing on in the coming days.

**Comment by cmvanmeter** [comment]
The current problem is that fgets grabs MAXLEN, does its thing, and then immediate grabs the next amount until end or MAXLEN, does its things, and so forth. Not particularly harmful, but this results in the program running multiple commands from a single line. I consider this unintended (non-graceful) behavior. The program should throw an error when input > MAXLEN and executes the input gracefull.
