### ISSUE TITLE
bug list

### ISSUE THREAD

**Issue by aaronmueller** [aaronmueller/zsh-P4#31]
* variables can contain special characters in their names, including quotes (makes everything act weird)
* imbalanced quotes aren't eliminated from variable values or names when using 'set'
* 'back' makes the next command print without a prompt (workingProgram does this too)
* manually-set prompts can't contain spaces, when the default prompt does contain spaces (workingProgram does this too)
* FATAL BUG: using 'do <command_that_doesn't_work>' deletes all portions of PATH after the first colon

**Comment by cmvanmeter** [comment]
### Fixed the following:
* variables can no longer contain special characters in their names
### Document and move-on (do not need to fix)
* 'back' make the next command print without a prompt (there is a prompt, it just prints weird b/c of background process timing)
* manually-set prompts can't contain spaces, when the default prompt does contain spaces
* the ctrl-d x2 thing
### FATAL BUG behavior
The primary fault with the bug is not deleting all portions of PATH -- see below example. I'm still trying to figure out what is happening.
```
nsh > dshv
tokens: 'dshv'
0: PATH = /bin:/usr/bin
1: ShowTokens = 1
nsh > do notreal
notreal: No such file or directory
nsh > dshv
0: PATH = /bin % truncated
1: ShowTokens = 0 % reset to 0
nsh > done % does not exit program
nsh > dshv
0: PATH = /bin:/usr/bin % reset to default
1: ShowTokens = 0 % still at 0
nsh > done % exits this time
```

**Comment by cmvanmeter** [comment]
For imbalanced quotes: I say we just remove the first and last quote if there is a pair. Treat any extras as being intentional.
### Exampes
"value" -> value
"value -> "value
""value"" -> "value"

**Comment by cmvanmeter** [comment]
Fixed primary issue with do. However, do still only checks the first part of path -- I'll still need to mess with it to make it work.

**Comment by cmvanmeter** [comment]
### doCmd() is FIXED!

**Comment by cmvanmeter** [comment]
Imbalanced quotes are handled. Need to describe in README.md
